# Task 1 – Data Preprocessing for Machine Learning

Before feeding data into any model, we need to clean and prepare it. This notebook walks through the standard preprocessing steps on the Iris dataset: checking for missing values, encoding labels, normalising features, and splitting into train/test sets.

**Dataset:** Iris (built-in via seaborn — no local file needed)  
**Steps covered:** missing-value check → label encoding → Min-Max normalisation → train/test split

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.model_selection import train_test_split

##  Load the Dataset

In [2]:
# Using seaborn's built-in copy of Iris so the notebook runs anywhere
iris = sns.load_dataset('iris')

print(f"Shape: {iris.shape}")
iris.head()

Shape: (150, 5)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

##  Explore & Check for Missing Values

In [3]:
# A quick look at column types and non-null counts
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [4]:
# Check if any column has nulls — ideally all zeros here
print("Missing values per column:")
print(iris.isnull().sum())

Missing values per column:
sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

##  Encode the Target Label

The `species` column is a string category. We convert it to integers (0, 1, 2) so sklearn models can work with it.

In [5]:
le = LabelEncoder()
iris['species'] = le.fit_transform(iris['species'])

# Show the mapping so it's clear what each number means
print("Label mapping:", dict(zip(le.classes_, le.transform(le.classes_))))
iris.head()

Label mapping: {'setosa': np.int64(0), 'versicolor': np.int64(1), 'virginica': np.int64(2)}

   sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

##  Normalise Features

Min-Max scaling brings all features into [0, 1]. This prevents features with large ranges (like petal length) from dominating distance-based models.

In [6]:
X = iris.drop('species', axis=1)
y = iris['species']

scaler = MinMaxScaler()
X_scaled = pd.DataFrame(scaler.fit_transform(X), columns=X.columns)

print("Feature ranges after scaling:")
print(X_scaled.describe().loc[['min', 'max']])

Feature ranges after scaling:
     sepal_length  sepal_width  petal_length  petal_width
min           0.0          0.0           0.0          0.0
max           1.0          1.0           1.0          1.0

##  Train / Test Split

We reserve 20 % of the data for evaluation. Setting `random_state` makes the split reproducible.

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)

print(f"Training samples : {len(X_train)}")
print(f"Test samples     : {len(X_test)}")

Training samples : 120
Test samples     : 30